VacationSpots12.1/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace VacationSpots12._1.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

VacationSpots12.1/Controllers/VacationController.cs
using VacationSpots12._1.Models;
using VacationSpots12._1.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace VacationSpots12._1.Controllers
{
    public class VacationController : Controller
    {
        private IData _tempdata;
        //dependency injection

        public VacationController (IData tempdata)
        {
            _tempdata = tempdata;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")] //prompt the user to login first
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create(Vacation obj)
        {
            if (ModelState.IsValid) //validation
            {
                _tempdata.AddVacation(obj);
                ViewBag.Message = "Vacation added successfully!";
            }
            return View(obj);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            Vacation obj = _tempdata.GetVacation(id);
            return View(obj);
        }

        [HttpPost]
        public IActionResult Edit(Vacation obj, int id)
        {
            obj.Id = id;
            _tempdata.UpdateVacation(obj);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            _tempdata.DeleteVacation(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int? id)
        {
            var vac = _tempdata.GetVacation(id);

            if (vac == null)
            {

                return NotFound();

            }

            return View(vac);
        }

        //sending the list of employees to the view 
        public IActionResult Index()
        {
            IndexViewModel model = new IndexViewModel(); //temp class 
            model.Vacations = _tempdata.ReadAll();
            return View(model);
        }
    }
}

VacationSpots12.1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VacationSpots12._1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VacationSpots12._1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vacation" asp-action="Index">Vacations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        @if (User.Identity.IsAuthenticated)
        {
            
            <h3>WELCOME @User.Identity.Name</h3>

        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @*This is method replaces the actual content of the view e.g Create/Details view*@
            @*This page decides the location of where the data is placed hence the @render *@

            @RenderBody()
            @RenderSection("section1", false) @*definition is given by the view itself*@



        </main>
    </div>

    <footer class="border-top footer text-muted">

        @RenderSection("Footer", false)

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VacationSpots12.1/Views/Shared/_LayoutCategory.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VacationSpots12._1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style=" background-color:goldenrod">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VacationSpots12._1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @*This is method replaces the actual content of the view e.g Create/Details view*@

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - VacationSpots12._1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>